"use client"
import type { Metadata } from "next";
import localFont from "next/font/local";
import "./globals.css";
const gilroyRegular = localFont({ src: "../public/fonts/Gilroy-Regular.ttf" });
import { Provider } from "react-redux";
import { store } from "@/redux/store";
import 'animate.css';

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${gilroyRegular.className}`}>
        <Provider store={store}>{children}</Provider>
      </body>
    </html>
  );
}
